name: Publish PR Version

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node and install dependencies
        uses: codfish/actions/setup-node-and-install@v3
        with:
          node-version: lts/*

      - name: Build package
        run: npm run build --if-present

      - name: Create package tarball
        run: npm pack

      - name: Upload package tarball
        uses: actions/upload-artifact@v6
        with:
          name: package-tarball
          path: '*.tgz'
          retention-days: 1

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read # To checkout base branch
      pull-requests: write # To comment on PR

    steps:
      - name: Checkout base branch
        uses: actions/checkout@v6

      - name: Setup Node
        uses: codfish/actions/setup-node-and-install@v3
        with:
          node-version: lts/*

      - name: Download package tarball
        uses: actions/download-artifact@v7
        with:
          name: package-tarball

      - name: Publish PR package
        uses: codfish/actions/npm-publish-pr@fix/tarball-mode-auth
        with:
          tarball: '*.tgz'
          npm-token: ${{ secrets.NPM_TOKEN }}
